//
//  AddCategoryViewModel.swift
//  ExpanseTracker
//
//  Created by Rayaheen Mseri on 18/10/1446 AH.
//

import SwiftUI
import CoreData
import Combine

class CategoryFunctionallityViewModel: ObservableObject {
    private let context = PersistanceController.shared.context
    
    func saveCategoryToCoreData(category: Category, userId: String) {
        print("save category to core data")
        
        // Create a fetch request to find the user by id
        let userRequest: NSFetchRequest<UserEntity> = UserEntity.fetchRequest()
        // Filter the results
        userRequest.predicate = NSPredicate(format: "id == %@", userId)
        userRequest.fetchLimit = 1
        
        do{
            // Fetch the first user that matches the predicate
            if let existingUserEntity = try context.fetch(userRequest).first {
                
                // Create a new CategoryEntity instance in the context
                let newCategory = CategoryEntity(context: context)
                newCategory.id = category.id
                newCategory.name = category.name
                newCategory.color = category.color
                newCategory.icon = category.icon
                newCategory.categoryType = category.categoryType?.rawValue
                newCategory.budgetLimit = category.budgetLimit ?? 0.0
                
                // Add the new category to the user list of categories
                // addToCategory is a method automatically generated by Core Data for the one-to-many relationship between UserEntity and CategoryEntity
                existingUserEntity.addToCategory(newCategory)
                print("✅ Added new category for the user.")
                
                PersistanceController.shared.saveContext()
            }
            else {
                print("No user found with id: \(userId)")
            }
        }catch {
            print("❌ Failed to save context: \(error)")
        }
    }
    
    func checkCategoryExist(category: Category, userId: String, userBudget: Double) -> (Bool , String) {
        print("Check if category exist")
        // Create a fetch request to find the user by id
        let userRequest: NSFetchRequest<UserEntity> = UserEntity.fetchRequest()
        // Filter the results
        userRequest.predicate = NSPredicate(format: "id == %@", userId)
        userRequest.fetchLimit = 1
        do{
            // Fetch the first user that matches the predicate
            if let existingUserEntity = try context.fetch(userRequest).first {
                
                let existingCategories = existingUserEntity.category?.allObjects as? [CategoryEntity] ?? []
                
                var budgetLimit = Int(category.budgetLimit ?? 0)
                
                for existingCategory in existingCategories {
                    
                    // Skip the check if editing the same category
                    if let existingCategoryId = existingCategory.id, existingCategoryId == category.id {
                        continue
                    }
                    
                    budgetLimit += Int(existingCategory.budgetLimit)
                    print("========= \(budgetLimit)")
                    
                    if existingCategory.name == category.name {
                        print("Category already exist")
                        return (true, "Category already exist")
                    }
                    
                    if existingCategory.color == category.color {
                        print("Color already exist")
                        return (true, "Color already exist")
                    }
                    
                    if category.budgetLimit == 0.0 {
                        print("Budget limit cannot be zero")
                        return (true, "Budget limit cannot be zero")
                    }
                }
                
                if budgetLimit > Int(userBudget) {
                    print("You have exceeded your budget limit")
                    return (true, "You have exceeded your budget limit")
                }
                return (false, "")
            }
            else {
                print("No user found with id: \(userId)")
            }
        }catch {
            print("❌ Failed to save context: \(error)")
        }
        return (false, "")
    }
    
    
    func fetchCategoryFromCoreDataWithId(categoryId: String, userId: String) -> Category? {
        print("Fetching category with id: \(categoryId)")
        
        // Create a fetch request to find the user by id
        let userRequest: NSFetchRequest<UserEntity> = UserEntity.fetchRequest()
        // Filter the results
        userRequest.predicate = NSPredicate(format: "id == %@", userId)
        userRequest.fetchLimit = 1
        
        do {
            // Fetch the first user that matches the predicate
            if let user = try context.fetch(userRequest).first {
                // Check if the user has categories and find the category and then finds the first category whose id matches the categoryId
                if let matchedCategory = user.category?
                    .compactMap({ $0 as? CategoryEntity })
                    .first(where: { $0.id == categoryId }) {
                    
                    // Create Category object
                    let category = Category(
                        id: matchedCategory.id ?? "",
                        name: matchedCategory.name ?? "",
                        color: matchedCategory.color ?? "",
                        icon: matchedCategory.icon ?? "",
                        categoryType: CategoryType(rawValue: matchedCategory.categoryType ?? "") ?? .other,
                        budgetLimit: matchedCategory.budgetLimit
                    )
                    
                    print("✅ Found category: \(category.name ?? "")")
                    return category
                } else {
                    print("❌ Category with id \(categoryId) not found in user's categories")
                    return nil
                }
            } else {
                print("❌ User with id \(userId) not found")
                return nil
            }
        } catch {
            print("❌ Error fetching user or category: \(error)")
            return nil
        }
    }
    
    func saveEditedCategory(category: Category, userId: String) {
        // Create a fetch request to find the user by id
        let userRequest: NSFetchRequest<UserEntity> = UserEntity.fetchRequest()
        // Filter the results
        userRequest.predicate = NSPredicate(format: "id == %@", userId)
        userRequest.fetchLimit = 1
        
        do {
            // Fetch the first user that matches the predicate
            if let user = try context.fetch(userRequest).first {
                // Check if the user has categories and find the category and then finds the first category whose id matches the categoryId
                if let matchedCategory = user.category?
                    .compactMap({ $0 as? CategoryEntity })
                    .first(where: { $0.id == category.id }) {
                    
                    // Update the Core Data object
                    matchedCategory.name = category.name
                    matchedCategory.icon = category.icon
                    matchedCategory.color = category.color
                    matchedCategory.categoryType = category.categoryType?.rawValue
                    matchedCategory.budgetLimit = category.budgetLimit ?? 0.0
                    
                    // Save the context
                    PersistanceController.shared.saveContext()
                    print("✅ Category updated successfully.")
                }
            } else {
                print("No category found with id: \(category.id ?? "")")
            }
        } catch {
            print("❌ Failed to save context: \(error)")
        }
    }
    
}
